update n_init for kmeans
IntelPython/scikit-learn_bench pull request #153
Opened 2024-08-08 13:33 UTC by md-shafiul-alam

For kmeans++, the default n_init=1 https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/cluster/_kmeans.py#L346.

Probably makes sense to benchmark the default behavior.

2024-08-21 10:27 UTC, Alexsandruss commented
@md-shafiul-alam 

> Change normalize to false

But why? KMeans inertia is sensitive to normalization

2024-08-21 12:11 UTC, md-shafiul-alam commented
> @md-shafiul-alam
> 
> > Change normalize to false
> 
> But why? KMeans inertia is sensitive to normalization

Only reason is that stock scikit learn does not have any option for normalization.

2024-08-22 08:13 UTC, Alexsandruss commented
`data:preprocessing_kwargs:normalize` is not argument of an estimator

2024-08-22 12:04 UTC, md-shafiul-alam commented
> `data:preprocessing_kwargs:normalize` is not argument of an estimator

I understand, but is there a specific reason we normalize by default? To me seems like a redundant step.

2024-08-23 08:37 UTC, Alexsandruss requested changes
> > `data:preprocessing_kwargs:normalize` is not argument of an estimator
> 
> I understand, but is there a specific reason we normalize by default? To me seems like a redundant step.

Normalization is required for algorithms sensitive to it for better quality metrics and representation of user cases.

2024-08-28 10:36 UTC, md-shafiul-alam commented
@Alexsandruss Do you suggest any more changes?

2024-08-28 10:59 UTC, Alexsandruss approved these changes

2024-08-28 11:00 UTC, merged