Report generator
IntelPython/scikit-learn_bench pull request #38
Opened 2020-10-09 08:38 UTC by Alexsandruss

Excel table generator from json outputs.

2020-10-10 20:08 UTC, PetrovKP requested changes
all scripts with the generator move to a separate folder. in this folder, create README.md - how to use.

2020-10-11 13:30 UTC, Alexsandruss commented
> all scripts with the generator move to a separate folder. in this folder, create README.md - how to use.

But there is only one script file and one config file, do they need separate folder?

2020-10-13 00:38 UTC, PetrovKP commented
> > all scripts with the generator move to a separate folder. in this folder, create README.md - how to use.
> 
> But there is only one script file and one config file, do they need separate folder?

@Alexsandruss , Yes, all auxiliary tools are best placed in a separate folder. in addition, there will be a separate start-up instructions.

2020-12-16 01:43 UTC, PetrovKP approved these changes

2020-12-16 01:43 UTC, merged